### ISSUE TITLE
Delete profile button needs more information

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/cfde-deriva#264]
This is not a release blocker.

When I go to my profile page: https://app-staging.nih-cfde.org/chaise/record/#registry/CFDE:user_profile/RID=PZ6 
it gives me the option to delete it. It does ask me if I'm sure, which is good, but it doesn't tell me what deleting will do. 

I experimented and it deletes my favorites and whatnot, but does not actually remove my profile from the site, and doesn't remove me from Globus. We should probably rename it to something like "reset to defaults" and have the popup say something like "this will delete all your preferences but will not remove your account. To completely remove your account do" whatever it is they'd have to do.

**Comment by jrchudy** [comment]
We pushed a changed to make the user_profile "non-deletable" until we can discuss what "deleting" your own user means in the world of CFDE.

**Comment by karlcz** [comment]
The changes we made disable create/copy/edit but I still see an active
delete button on staging...

**Comment by karlcz** [comment]
A new patch completely disables these edit controls on user_profile for now.  Applied to dev and staging.
